spring:
  application:
    name: auth-service
  cloud:
    config:
      name: auth-service
  config:
    import: "optional:configserver:"
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true